services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole_2
    hostname: UGREEN-NAS
    restart: unless-stopped

    ports:
      - "192.168.10.28:53:53/tcp"
      - "192.168.10.28:53:53/udp"
      - "90:80"
      - "8443:443"

    environment:
      TZ: "Europe/Madrid"
      FTLCONF_webserver_api_password: ""
      FTLCONF_dns_listeningMode: "ALL"

    volumes:
      - ./etc-pihole:/etc/pihole

    cap_add:
      - SYS_NICE

    depends_on:
      - unbound

    networks:
      - dns_net

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped

    networks:
      - dns_net

networks:
  dns_net:
    driver: bridge
