services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    networks:
      - pihole_net

    ports:
      - "8080:80"
      - "1053:53/tcp"
      - "1053:53/udp"

    environment:
      TZ: "Europe/Madrid"
      WEBPASSWORD: "admin"
      DNSMASQ_USER: "root"

    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d

    restart: unless-stopped

networks:
  pihole_net:
    external: true
